openapi: 3.1.0
info:
  title: Library Management API
  description: API for managing books and authors in a library.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1

paths:
  /books:
    get:
      summary: Get a list of books
      parameters:
        - name: bookName
          in: query
          description: Filter by book name
          schema:
            type: string
        - name: startDate
          in: query
          description: Filter by release date (start of range)
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: Filter by release date (end of range)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of books
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'

    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '201':
          description: Book created

    put:
      summary: Update a book (idempotent)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: Book updated

    delete:
      summary: Delete a book
      parameters:
        - name: id
          in: query
          description: ID of the book to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Book deleted successfully

  /authors:
    get:
      summary: Get a list of authors
      parameters:
        - name: authorName
          in: query
          description: Filter by author name
          schema:
            type: string
      responses:
        '200':
          description: List of authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'

    post:
      summary: Add a new author
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Author created

    put:
      summary: Update an author (idempotent)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
      responses:
        '200':
          description: Author updated

    delete:
      summary: Delete an author
      parameters:
        - name: id
          in: query
          description: ID of the author to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Author deleted successfully

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        author:
          type: string
          description: Name of the author
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date

    Author:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - M
            - F
